### PR TITLE
fix(faucet): handling windows time

### LINKED ISSUE #7: Moving window can become frequently unaligned
There is a clear window within the smart contract of how many tokens can be given within the interval, however in this implementation the window movement isn’t clearly defined. It is based on when the next claim starts instead of the end of the previous window, leaving gaps in the timeline. 

The optimal solution would be that each window starts at exactly the moment the previous window ends, so that the total amount of tokens given over the broader timeline is expressed deterministically. For instance; 24 hours and 1000 tokens should equal no more and **no less** than 365,000 tokens over 1 year. 

https://github.com/edenia/ultra-faucet/blob/main/faucet/src/faucet.cpp#L45

### PR DESCRIPTION
**Pull request by leisterfrancisco**
### What does this PR do?

- Resolve #7

### Steps to test

1. Transfer tokens from the faucet account.
2. Validate window transfer time is correct without losing alignment

### CODE REVIEW

File: faucet/src/faucet.cpp [hunk 1]
```diff
@@ -40,16 +40,20 @@ namespace faucets {
 
     check(faucet_itr != _faucet.end(), "Faucet does not exist");
 
-    if(current_time_point() - faucet_itr->started_at >= seconds(faucet_itr->interval.sec_since_epoch())) {
+    time_point now = current_time_point();
+    if(now > faucet_itr->until) {
+      uint32_t intervalSecs = faucet_itr->interval.sec_since_epoch();
+      float windowGap = (now.sec_since_epoch() - faucet_itr->until.sec_since_epoch()) / intervalSecs;
+      
+      time_point newUntil = faucet_itr->until + seconds(intervalSecs) + time_point(seconds(floor(windowGap) * intervalSecs));
```
Comment (leisterfrancisco) [inline faucet/src/faucet.cpp:48]: this line makes the correction window time if for some reason the faucet account doesn't claim its corresponding tokens

**Review by xavier506 — APPROVED** [review]
LGTM
